# Site settings
title: Kishan Kumar Maurya
description: Mobile Full Stack Engineer at Cashfree Payments & Technical writer at MindOrks & ProAndroidDev.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kishan Maurya
user_description: Mobile Full Stack Engineer with a experience in developing Payment SDKs, EV mobile apps, E-commerce, Cab Booking, Media, Health applications. Skilled in Kotlin, Android, Core Java, NodeJs, SpringBoot, CI/CD, Jenkins, Algorithms and design patterns. Familiar with latest latest Architectures, Frameworks.
user_title: Mobile Full Stack Engineer
email: kishankr.maurya@gmail.com
twitter_username: KishankrMaurya
github_username:  droiddevgeeks
linkedin_username : kishan-maurya
facebook_username : kishankr.maurya

exclude: ['package.json', 'src' , 'node_modules']
